name: Build and Release NeonRacer

on:
  push:
    tags:
      - 'v*.*'  # Trigger on version tags like v1.0, v1.1, etc.

jobs:
  build-linux:
    name: Build Linux Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build Linux App and Installer
        run: ./gradlew jPackageAll

      - name: Create GitHub Release (Linux)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Installers
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/jpackage/NeonRacer-*.deb
            build/jpackage/NeonRacer-*-app-image.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build Windows App and Installer
        run: ./gradlew jPackageAll

      - name: Upload Windows Installer
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/jpackage/NeonRacer-*.exe
            build/jpackage/NeonRacer-*-app-image.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS Installer
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build macOS App and Installer
        run: ./gradlew jPackageAll

      - name: Upload macOS Installer
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/jpackage/NeonRacer-*.dmg
            build/jpackage/NeonRacer-*-app-image.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
