name: Build and Release NeonRacer

on:
  push:
    tags:
      - 'v*.*'  # Trigger on version tags like v1.0, v1.1, etc.
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    name: Build Linux(Debian) App Image & Installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build Linux App and Installer
        run: ./gradlew jPackageAll

      - name: Create GitHub Release (Linux)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Linux Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            app/build/jpackage/neon-racer-*.deb
            app/build/jpackage/neon-racer-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux-fedora:
    name: Build Linux (Fedora) Installer
    runs-on: ubuntu-latest
    container: fedora:latest
    needs: build-linux
    steps:
      - name: Install dependencies
        run: |
          dnf install -y java-24-openjdk-devel rpm-build git
          export JAVA_HOME=/usr/lib/jvm/java-24-openjdk
          export PATH=$JAVA_HOME/bin:$PATH
      - uses: actions/checkout@v5
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build Fedora Installer
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-24-openjdk
          export PATH=$JAVA_HOME/bin:$PATH
          ./gradlew jPackageAll
      - name: Upload Fedora Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            app/build/jpackage/neon-racer-*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build Windows App & Installer
    runs-on: windows-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build Windows App and Installer
        run: ./gradlew jPackageAll

      - name: Upload Windows Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            app/build/jpackage/neon-racer-*.exe
            app/build/jpackage/neon-racer-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS App & Installer
    runs-on: macos-latest
    needs: build-windows
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 24

      - name: Build macOS App and Installer
        run: ./gradlew jPackageAll

      - name: Upload macOS Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            app/build/jpackage/neon-racer-*.dmg
            app/build/jpackage/neon-racer-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
